FROM node:25 AS base

FROM base AS project
WORKDIR /usr/project
COPY . .
RUN ls -la

FROM project AS dev
CMD ["echo", "base > project > dev"]

FROM dev AS dist
RUN mkdir -p dist
RUN echo "prod" > dist/artifact.txt

FROM node:lts-alpine AS release
WORKDIR /opt/app
COPY --from=dist /usr/project/dist ./dist

FROM release AS app
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nodejs -u 1001
USER nodejs
CMD ["cat", "dist/artifact.txt"]
