FROM node:25 AS base

FROM base AS project
WORKDIR /usr/project
COPY . .
RUN ls -la

FROM project AS dev
RUN echo "base > dev"
CMD ["echo", "base > dev > tested"]

FROM dev AS dist
RUN echo "base > dev > dist"

FROM project AS release
RUN echo "base > release"
CMD ["echo", "base > release > final"]
