name: docker build target
description: docker build target and scan image

# NOTE: Fixes "Error: Resource not accessible by integration"
# permissions:
#   contents: read
#   security-events: write

inputs:
  target:
    description: Docker target to build
    required: true

  repository_name:
    description: Repository name
    required: false
    default: ${{ github.event.repository.name }}

  dockerfile:
    description: Dockerfile to use for build
    required: false
    default: Dockerfile

  image_tag_suffix:
    description: Suffix to append to the image tag
    required: false
    default: latest

  docker_cli_options:
    description: Additional options to pass to the docker build command
    required: false
    default: "--no-cache"

  #
  # scan-image
  fail-build:
    description: Fail the build if vulnerabilities are found
    required: false
    default: "false"

  severity-cutoff:
    description: The minimum severity level to report
    required: false
    default: "high"

  only-fixed:
    description: Only report vulnerabilities that have been fixed
    required: false
    default: "false"

runs:
  using: composite

  steps:
    - name: "docker build: ${{ inputs.dockerfile }}"
      shell: bash
      run: |
        docker build . \
          ${{ inputs.docker_cli_options }} \
          --file ${{ inputs.dockerfile }} \
          --target ${{ inputs.target }} \
          --tag ${{ inputs.repository_name }}.${{ inputs.target }}:${{ inputs.image_tag_suffix }}

    - uses: percebus/github-actions-containerization/.github/actions/scan-image@main
      if: github.ref == 'refs/heads/main'
      with:
        image_tag: ${{ inputs.repository_name }}.${{ inputs.target }}:${{ inputs.image_tag_suffix }}
        fail-build: ${{ inputs.fail-build }}
        severity-cutoff: ${{ inputs.severity-cutoff }}
        only-fixed: ${{ inputs.only-fixed }}
